title: Valetudo
description: >-
  Easily find and connect Valetudo robot vacuums on and to your network.
baseurl: ""
url: https://companion.valetudo.cloud
github_username: Hypfer

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
collections:
  pages:
    output: true
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
